CREATE DATABASE pokedex_manager;
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);
ALTER TABLE users ADD COLUMN password varchar(255) not null;
delete from users; 
ALTER TABLE users AUTO_INCREMENT = 1;
truncate table users;
delete from user_collections;
UPDATE user_collections SET status = UPPER(status);
ALTER TABLE user_collections MODIFY COLUMN status ENUM('OWNED', 'WISHLIST') NOT NULL;


CREATE TABLE pokemon (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type1 VARCHAR(50),
    type2 VARCHAR(50),
    generation INT,
    stats JSON,
    image_url VARCHAR(255)
);

CREATE TABLE user_collections (
    user_id INT,
    pokemon_id INT,
    status ENUM('owned', 'wishlist') NOT NULL,
    PRIMARY KEY (user_id, pokemon_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (pokemon_id) REFERENCES pokemon(id)
);
CREATE TABLE evolutions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    base_pokemon_id INT NOT NULL,
    evolved_pokemon_id INT NOT NULL,
    evolution_trigger VARCHAR(255),
    trigger_detail VARCHAR(255),
    FOREIGN KEY (base_pokemon_id) REFERENCES pokemon(id),
    FOREIGN KEY (evolved_pokemon_id) REFERENCES pokemon(id)
);
INSERT INTO pokemon (id, name, type1, type2, generation, stats, image_url) VALUES
-- Pokémon di prima generazione
(1, 'Bulbasaur', 'Grass', 'Poison', 1, '{"hp":45,"attack":49,"defense":49,"speed":45}', 'https://img.pokemondb.net/artwork/bulbasaur.jpg'),
(2, 'Ivysaur', 'Grass', 'Poison', 1, '{"hp":60,"attack":62,"defense":63,"speed":60}', 'https://img.pokemondb.net/artwork/ivysaur.jpg'),
(3, 'Venusaur', 'Grass', 'Poison', 1, '{"hp":80,"attack":82,"defense":83,"speed":80}', 'https://img.pokemondb.net/artwork/venusaur.jpg'),
(4, 'Charmander', 'Fire', NULL, 1, '{"hp":39,"attack":52,"defense":43,"speed":65}', 'https://img.pokemondb.net/artwork/charmander.jpg'),
(5, 'Charmeleon', 'Fire', NULL, 1, '{"hp":58,"attack":64,"defense":58,"speed":80}', 'https://img.pokemondb.net/artwork/charmeleon.jpg'),
(6, 'Charizard', 'Fire', 'Flying', 1, '{"hp":78,"attack":84,"defense":78,"speed":100}', 'https://img.pokemondb.net/artwork/charizard.jpg'),
(7, 'Squirtle', 'Water', NULL, 1, '{"hp":44,"attack":48,"defense":65,"speed":43}', 'https://img.pokemondb.net/artwork/squirtle.jpg'),
(8, 'Wartortle', 'Water', NULL, 1, '{"hp":59,"attack":63,"defense":80,"speed":58}', 'https://img.pokemondb.net/artwork/wartortle.jpg'),
(9, 'Blastoise', 'Water', NULL, 1, '{"hp":79,"attack":83,"defense":100,"speed":78}', 'https://img.pokemondb.net/artwork/blastoise.jpg'),
(10, 'Caterpie', 'Bug', NULL, 1, '{"hp":45,"attack":30,"defense":35,"speed":45}', 'https://img.pokemondb.net/artwork/caterpie.jpg'),
(11, 'Metapod', 'Bug', NULL, 1, '{"hp":50,"attack":20,"defense":55,"speed":30}', 'https://img.pokemondb.net/artwork/metapod.jpg'),
(12, 'Butterfree', 'Bug', 'Flying', 1, '{"hp":60,"attack":45,"defense":50,"speed":70}', 'https://img.pokemondb.net/artwork/butterfree.jpg'),
(13, 'Weedle', 'Bug', 'Poison', 1, '{"hp":40,"attack":35,"defense":30,"speed":50}', 'https://img.pokemondb.net/artwork/weedle.jpg'),
(14, 'Kakuna', 'Bug', 'Poison', 1, '{"hp":45,"attack":25,"defense":50,"speed":35}', 'https://img.pokemondb.net/artwork/kakuna.jpg'),
(15, 'Beedrill', 'Bug', 'Poison', 1, '{"hp":65,"attack":90,"defense":40,"speed":75}', 'https://img.pokemondb.net/artwork/beedrill.jpg'),
(16, 'Eevee', 'Normal', NULL, 1, '{"hp":55,"attack":55,"defense":50,"speed":55}', 'https://img.pokemondb.net/artwork/eevee.jpg'),
(17, 'Vaporeon', 'Water', NULL, 1, '{"hp":130,"attack":65,"defense":60,"speed":65}', 'https://img.pokemondb.net/artwork/vaporeon.jpg'),
(18, 'Jolteon', 'Electric', NULL, 1, '{"hp":65,"attack":65,"defense":60,"speed":130}', 'https://img.pokemondb.net/artwork/jolteon.jpg'),
(19, 'Flareon', 'Fire', NULL, 1, '{"hp":65,"attack":130,"defense":60,"speed":65}', 'https://img.pokemondb.net/artwork/flareon.jpg'),
-- Pokémon di seconda generazione
(20, 'Espeon', 'Psychic', NULL, 2, '{"hp":65,"attack":65,"defense":60,"speed":110}', 'https://img.pokemondb.net/artwork/espeon.jpg'),
(21, 'Umbreon', 'Dark', NULL, 2, '{"hp":95,"attack":65,"defense":110,"speed":65}', 'https://img.pokemondb.net/artwork/umbreon.jpg'),
(22, 'Togepi', 'Fairy', NULL, 2, '{"hp":35,"attack":20,"defense":65,"speed":20}', 'https://img.pokemondb.net/artwork/togepi.jpg'),
(23, 'Togetic', 'Fairy', 'Flying', 2, '{"hp":55,"attack":40,"defense":85,"speed":40}', 'https://img.pokemondb.net/artwork/togetic.jpg'),
(24, 'Togekiss', 'Fairy', 'Flying', 2, '{"hp":85,"attack":50,"defense":95,"speed":80}', 'https://img.pokemondb.net/artwork/togekiss.jpg'),
(25, 'Chikorita', 'Grass', NULL, 2, '{"hp":45,"attack":49,"defense":65,"speed":45}', 'https://img.pokemondb.net/artwork/chikorita.jpg'),
(26, 'Bayleef', 'Grass', NULL, 2, '{"hp":60,"attack":62,"defense":80,"speed":60}', 'https://img.pokemondb.net/artwork/bayleef.jpg'),
(27, 'Meganium', 'Grass', NULL, 2, '{"hp":80,"attack":82,"defense":100,"speed":80}', 'https://img.pokemondb.net/artwork/meganium.jpg'),
(28, 'Cyndaquil', 'Fire', NULL, 2, '{"hp":39,"attack":52,"defense":43,"speed":65}', 'https://img.pokemondb.net/artwork/cyndaquil.jpg'),
(29, 'Quilava', 'Fire', NULL, 2, '{"hp":58,"attack":64,"defense":58,"speed":80}', 'https://img.pokemondb.net/artwork/quilava.jpg'),
(30, 'Typhlosion', 'Fire', NULL, 2, '{"hp":78,"attack":84,"defense":78,"speed":100}', 'https://img.pokemondb.net/artwork/typhlosion.jpg'),
(31, 'Totodile', 'Water', NULL, 2, '{"hp":50,"attack":65,"defense":64,"speed":43}', 'https://img.pokemondb.net/artwork/totodile.jpg'),
(32, 'Croconaw', 'Water', NULL, 2, '{"hp":65,"attack":80,"defense":80,"speed":58}', 'https://img.pokemondb.net/artwork/croconaw.jpg'),
(33, 'Feraligatr', 'Water', NULL, 2, '{"hp":85,"attack":105,"defense":100,"speed":78}', 'https://img.pokemondb.net/artwork/feraligatr.jpg'),
(34, 'Sentret', 'Normal', NULL, 2, '{"hp":35,"attack":46,"defense":34,"speed":20}', 'https://img.pokemondb.net/artwork/sentret.jpg'),
(35, 'Furret', 'Normal', NULL, 2, '{"hp":85,"attack":76,"defense":64,"speed":90}', 'https://img.pokemondb.net/artwork/furret.jpg'),
(36, 'Hoothoot', 'Normal', 'Flying', 2, '{"hp":60,"attack":30,"defense":30,"speed":50}', 'https://img.pokemondb.net/artwork/hoothoot.jpg'),
(37, 'Noctowl', 'Normal', 'Flying', 2, '{"hp":100,"attack":50,"defense":50,"speed":70}', 'https://img.pokemondb.net/artwork/noctowl.jpg'),
(38, 'Spinarak', 'Bug', 'Poison', 2, '{"hp":40,"attack":60,"defense":40,"speed":30}', 'https://img.pokemondb.net/artwork/spinarak.jpg'),
(39, 'Ariados', 'Bug', 'Poison', 2, '{"hp":70,"attack":90,"defense":70,"speed":40}', 'https://img.pokemondb.net/artwork/ariados.jpg'),
(40, 'Crobat', 'Poison', 'Flying', 2, '{"hp":85,"attack":90,"defense":80,"speed":130}', 'https://img.pokemondb.net/artwork/crobat.jpg'),
(41, 'Pichu', 'Electric', NULL, 2, '{"hp":20,"attack":40,"defense":15,"speed":60}', 'https://img.pokemondb.net/artwork/pichu.jpg'),
(42, 'Cleffa', 'Fairy', NULL, 2, '{"hp":50,"attack":25,"defense":28,"speed":15}', 'https://img.pokemondb.net/artwork/cleffa.jpg'),
(43, 'Igglybuff', 'Normal', 'Fairy', 2, '{"hp":90,"attack":30,"defense":15,"speed":15}', 'https://img.pokemondb.net/artwork/igglybuff.jpg'),
-- Pokémon di terza generazione
(44, 'Treecko', 'Grass', NULL, 3, '{"hp":40,"attack":45,"defense":35,"speed":70}', 'https://img.pokemondb.net/artwork/treecko.jpg'),
(45, 'Grovyle', 'Grass', NULL, 3, '{"hp":50,"attack":65,"defense":45,"speed":95}', 'https://img.pokemondb.net/artwork/grovyle.jpg'),
(46, 'Sceptile', 'Grass', NULL, 3, '{"hp":70,"attack":85,"defense":65,"speed":120}', 'https://img.pokemondb.net/artwork/sceptile.jpg'),
(47, 'Torchic', 'Fire', NULL, 3, '{"hp":45,"attack":60,"defense":40,"speed":45}', 'https://img.pokemondb.net/artwork/torchic.jpg'),
(48, 'Combusken', 'Fire', 'Fighting', 3, '{"hp":60,"attack":85,"defense":60,"speed":55}', 'https://img.pokemondb.net/artwork/combusken.jpg'),
(49, 'Blaziken', 'Fire', 'Fighting', 3, '{"hp":80,"attack":120,"defense":70,"speed":80}', 'https://img.pokemondb.net/artwork/blaziken.jpg'),
(50, 'Mudkip', 'Water', NULL, 3, '{"hp":50,"attack":70,"defense":50,"speed":40}', 'https://img.pokemondb.net/artwork/mudkip.jpg'),
(51, 'Marshtomp', 'Water', 'Ground', 3, '{"hp":70,"attack":85,"defense":70,"speed":50}', 'https://img.pokemondb.net/artwork/marshtomp.jpg'),
(52, 'Swampert', 'Water', 'Ground', 3, '{"hp":100,"attack":110,"defense":90,"speed":60}', 'https://img.pokemondb.net/artwork/swampert.jpg'),
(53, 'Poochyena', 'Dark', NULL, 3, '{"hp":35,"attack":55,"defense":35,"speed":35}', 'https://img.pokemondb.net/artwork/poochyena.jpg'),
(54, 'Mightyena', 'Dark', NULL, 3, '{"hp":70,"attack":90,"defense":70,"speed":70}', 'https://img.pokemondb.net/artwork/mightyena.jpg'),
(55, 'Zigzagoon', 'Normal', NULL, 3, '{"hp":38,"attack":30,"defense":41,"speed":60}', 'https://img.pokemondb.net/artwork/zigzagoon.jpg'),
(56, 'Linoone', 'Normal', NULL, 3, '{"hp":78,"attack":70,"defense":61,"speed":100}', 'https://img.pokemondb.net/artwork/linoone.jpg'),
(57, 'Wurmple', 'Bug', NULL, 3, '{"hp":45,"attack":45,"defense":35,"speed":20}', 'https://img.pokemondb.net/artwork/wurmple.jpg'),
(58, 'Silcoon', 'Bug', NULL, 3, '{"hp":50,"attack":35,"defense":55,"speed":15}', 'https://img.pokemondb.net/artwork/silcoon.jpg'),
(59, 'Beautifly', 'Bug', 'Flying', 3, '{"hp":60,"attack":70,"defense":50,"speed":65}', 'https://img.pokemondb.net/artwork/beautifly.jpg'),
(60, 'Cascoon', 'Bug', NULL, 3, '{"hp":50,"attack":35,"defense":55,"speed":15}', 'https://img.pokemondb.net/artwork/cascoon.jpg'),
(61, 'Dustox', 'Bug', 'Poison', 3, '{"hp":60,"attack":50,"defense":70,"speed":65}', 'https://img.pokemondb.net/artwork/dustox.jpg'),
-- Pokémon di quarta generazione
(62, 'Turtwig', 'Grass', NULL, 4, '{"hp":55,"attack":68,"defense":64,"speed":31}', 'https://img.pokemondb.net/artwork/turtwig.jpg'),
(63, 'Grotle', 'Grass', NULL, 4, '{"hp":75,"attack":89,"defense":85,"speed":36}', 'https://img.pokemondb.net/artwork/grotle.jpg'),
(64, 'Torterra', 'Grass', 'Ground', 4, '{"hp":95,"attack":109,"defense":105,"speed":56}', 'https://img.pokemondb.net/artwork/torterra.jpg'),
(65, 'Chimchar', 'Fire', NULL, 4, '{"hp":44,"attack":58,"defense":44,"speed":61}', 'https://img.pokemondb.net/artwork/chimchar.jpg'),
(66, 'Monferno', 'Fire', 'Fighting', 4, '{"hp":64,"attack":78,"defense":52,"speed":81}', 'https://img.pokemondb.net/artwork/monferno.jpg'),
(67, 'Infernape', 'Fire', 'Fighting', 4, '{"hp":76,"attack":104,"defense":71,"speed":108}', 'https://img.pokemondb.net/artwork/infernape.jpg'),
(68, 'Piplup', 'Water', NULL, 4, '{"hp":53,"attack":51,"defense":53,"speed":40}', 'https://img.pokemondb.net/artwork/piplup.jpg'),
(69, 'Prinplup', 'Water', NULL, 4, '{"hp":64,"attack":66,"defense":68,"speed":50}', 'https://img.pokemondb.net/artwork/prinplup.jpg'),
(70, 'Empoleon', 'Water', 'Steel', 4, '{"hp":84,"attack":86,"defense":88,"speed":60}', 'https://img.pokemondb.net/artwork/empoleon.jpg'),
(71, 'Starly', 'Normal', 'Flying', 4, '{"hp":40,"attack":55,"defense":30,"speed":60}', 'https://img.pokemondb.net/artwork/starly.jpg'),
(72, 'Staravia', 'Normal', 'Flying', 4, '{"hp":55,"attack":75,"defense":50,"speed":80}', 'https://img.pokemondb.net/artwork/staravia.jpg'),
(73, 'Staraptor', 'Normal', 'Flying', 4, '{"hp":85,"attack":120,"defense":70,"speed":100}', 'https://img.pokemondb.net/artwork/staraptor.jpg'),
(74, 'Bidoof', 'Normal', NULL, 4, '{"hp":59,"attack":45,"defense":40,"speed":31}', 'https://img.pokemondb.net/artwork/bidoof.jpg'),
(75, 'Bibarel', 'Normal', 'Water', 4, '{"hp":79,"attack":85,"defense":60,"speed":55}', 'https://img.pokemondb.net/artwork/bibarel.jpg'),
(76, 'Shinx', 'Electric', NULL, 4, '{"hp":45,"attack":65,"defense":34,"speed":45}', 'https://img.pokemondb.net/artwork/shinx.jpg'),
(77, 'Luxio', 'Electric', NULL, 4, '{"hp":60,"attack":85,"defense":49,"speed":60}', 'https://img.pokemondb.net/artwork/luxio.jpg'),
(78, 'Luxray', 'Electric', NULL, 4, '{"hp":80,"attack":120,"defense":79,"speed":70}', 'https://img.pokemondb.net/artwork/luxray.jpg'),
(79, 'Budew', 'Grass', 'Poison', 4, '{"hp":40,"attack":30,"defense":35,"speed":55}', 'https://img.pokemondb.net/artwork/budew.jpg'),
(80, 'Roselia', 'Grass', 'Poison', 4, '{"hp":50,"attack":60,"defense":45,"speed":65}', 'https://img.pokemondb.net/artwork/roselia.jpg'),
(81, 'Roserade', 'Grass', 'Poison', 4, '{"hp":60,"attack":70,"defense":65,"speed":90}', 'https://img.pokemondb.net/artwork/roserade.jpg'),
-- Pokémon di quinta generazione
(82, 'Snivy', 'Grass', NULL, 5, '{"hp":45,"attack":45,"defense":55,"speed":63}', 'https://img.pokemondb.net/artwork/snivy.jpg'),
(83, 'Servine', 'Grass', NULL, 5, '{"hp":60,"attack":60,"defense":75,"speed":83}', 'https://img.pokemondb.net/artwork/servine.jpg'),
(84, 'Serperior', 'Grass', NULL, 5, '{"hp":75,"attack":75,"defense":95,"speed":113}', 'https://img.pokemondb.net/artwork/serperior.jpg'),
(85, 'Tepig', 'Fire', NULL, 5, '{"hp":65,"attack":63,"defense":45,"speed":45}', 'https://img.pokemondb.net/artwork/tepig.jpg'),
(86, 'Pignite', 'Fire', 'Fighting', 5, '{"hp":90,"attack":93,"defense":55,"speed":55}', 'https://img.pokemondb.net/artwork/pignite.jpg'),
(87, 'Emboar', 'Fire', 'Fighting', 5, '{"hp":110,"attack":123,"defense":65,"speed":65}', 'https://img.pokemondb.net/artwork/emboar.jpg'),
(88, 'Oshawott', 'Water', NULL, 5, '{"hp":55,"attack":55,"defense":45,"speed":45}', 'https://img.pokemondb.net/artwork/oshawott.jpg'),
(89, 'Dewott', 'Water', NULL, 5, '{"hp":75,"attack":75,"defense":60,"speed":60}', 'https://img.pokemondb.net/artwork/dewott.jpg'),
(90, 'Samurott', 'Water', NULL, 5, '{"hp":95,"attack":100,"defense":85,"speed":70}', 'https://img.pokemondb.net/artwork/samurott.jpg'),
(91, 'Patrat', 'Normal', NULL, 5, '{"hp":45,"attack":55,"defense":39,"speed":42}', 'https://img.pokemondb.net/artwork/patrat.jpg'),
(92, 'Watchog', 'Normal', NULL, 5, '{"hp":60,"attack":85,"defense":69,"speed":77}', 'https://img.pokemondb.net/artwork/watchog.jpg'),
(93, 'Lillipup', 'Normal', NULL, 5, '{"hp":45,"attack":60,"defense":45,"speed":55}', 'https://img.pokemondb.net/artwork/lillipup.jpg'),
(94, 'Herdier', 'Normal', NULL, 5, '{"hp":65,"attack":80,"defense":65,"speed":60}', 'https://img.pokemondb.net/artwork/herdier.jpg'),
(95, 'Stoutland', 'Normal', NULL, 5, '{"hp":85,"attack":110,"defense":90,"speed":80}', 'https://img.pokemondb.net/artwork/stoutland.jpg'),
(96, 'Purrloin', 'Dark', NULL, 5, '{"hp":41,"attack":50,"defense":37,"speed":66}', 'https://img.pokemondb.net/artwork/purrloin.jpg'),
(97, 'Liepard', 'Dark', NULL, 5, '{"hp":64,"attack":88,"defense":50,"speed":106}', 'https://img.pokemondb.net/artwork/liepard.jpg'),
(98, 'Pansage', 'Grass', NULL, 5, '{"hp":50,"attack":53,"defense":48,"speed":64}', 'https://img.pokemondb.net/artwork/pansage.jpg'),
(99, 'Simisage', 'Grass', NULL, 5, '{"hp":75,"attack":98,"defense":63,"speed":101}', 'https://img.pokemondb.net/artwork/simisage.jpg'),
(100, 'Panpour', 'Water', NULL, 5, '{"hp":50,"attack":53,"defense":48,"speed":64}', 'https://img.pokemondb.net/artwork/panpour.jpg'),
(101, 'Simipour', 'Water', NULL, 5, '{"hp":75,"attack":98,"defense":63,"speed":101}', 'https://img.pokemondb.net/artwork/simipour.jpg'),
(102, 'Pansear', 'Fire', NULL, 5, '{"hp":50,"attack":53,"defense":48,"speed":64}', 'https://img.pokemondb.net/artwork/pansear.jpg'),
(103, 'Simisear', 'Fire', NULL, 5, '{"hp":75,"attack":98,"defense":63,"speed":101}', 'https://img.pokemondb.net/artwork/simisear.jpg'),
-- Pokémon di sesta generazione
(104, 'Chespin', 'Grass', NULL, 6, '{"hp":56,"attack":61,"defense":65,"speed":38}', 'https://img.pokemondb.net/artwork/chespin.jpg'),
(105, 'Quilladin', 'Grass', NULL, 6, '{"hp":61,"attack":78,"defense":95,"speed":57}', 'https://img.pokemondb.net/artwork/quilladin.jpg'),
(106, 'Chesnaught', 'Grass', 'Fighting', 6, '{"hp":88,"attack":107,"defense":122,"speed":64}', 'https://img.pokemondb.net/artwork/chesnaught.jpg'),
(107, 'Fennekin', 'Fire', NULL, 6, '{"hp":40,"attack":45,"defense":40,"speed":60}', 'https://img.pokemondb.net/artwork/fennekin.jpg'),
(108, 'Braixen', 'Fire', NULL, 6, '{"hp":59,"attack":59,"defense":58,"speed":73}', 'https://img.pokemondb.net/artwork/braixen.jpg'),
(109, 'Delphox', 'Fire', 'Psychic', 6, '{"hp":75,"attack":69,"defense":72,"speed":104}', 'https://img.pokemondb.net/artwork/delphox.jpg'),
(110, 'Froakie', 'Water', NULL, 6, '{"hp":41,"attack":56,"defense":40,"speed":71}', 'https://img.pokemondb.net/artwork/froakie.jpg'),
(111, 'Frogadier', 'Water', NULL, 6, '{"hp":54,"attack":63,"defense":52,"speed":97}', 'https://img.pokemondb.net/artwork/frogadier.jpg'),
(112, 'Greninja', 'Water', 'Dark', 6, '{"hp":72,"attack":95,"defense":67,"speed":122}', 'https://img.pokemondb.net/artwork/greninja.jpg'),
(113, 'Bunnelby', 'Normal', NULL, 6, '{"hp":38,"attack":36,"defense":38,"speed":57}', 'https://img.pokemondb.net/artwork/bunnelby.jpg'),
(114, 'Diggersby', 'Normal', 'Ground', 6, '{"hp":85,"attack":56,"defense":77,"speed":78}', 'https://img.pokemondb.net/artwork/diggersby.jpg'),
(115, 'Fletchling', 'Normal', 'Flying', 6, '{"hp":45,"attack":50,"defense":43,"speed":62}', 'https://img.pokemondb.net/artwork/fletchling.jpg'),
(116, 'Fletchinder', 'Fire', 'Flying', 6, '{"hp":62,"attack":73,"defense":55,"speed":84}', 'https://img.pokemondb.net/artwork/fletchinder.jpg'),
(117, 'Talonflame', 'Fire', 'Flying', 6, '{"hp":78,"attack":81,"defense":71,"speed":126}', 'https://img.pokemondb.net/artwork/talonflame.jpg'),
(118, 'Scatterbug', 'Bug', NULL, 6, '{"hp":38,"attack":35,"defense":40,"speed":35}', 'https://img.pokemondb.net/artwork/scatterbug.jpg'),
(119, 'Spewpa', 'Bug', NULL, 6, '{"hp":45,"attack":22,"defense":60,"speed":29}', 'https://img.pokemondb.net/artwork/spewpa.jpg'),
(120, 'Vivillon', 'Bug', 'Flying', 6, '{"hp":80,"attack":52,"defense":50,"speed":89}', 'https://img.pokemondb.net/artwork/vivillon.jpg'),
(121, 'Litleo', 'Fire', 'Normal', 6, '{"hp":62,"attack":50,"defense":58,"speed":72}', 'https://img.pokemondb.net/artwork/litleo.jpg'),
(122, 'Pyroar', 'Fire', 'Normal', 6, '{"hp":86,"attack":68,"defense":72,"speed":106}', 'https://img.pokemondb.net/artwork/pyroar.jpg'),
(123, 'Rowlet', 'Grass', 'Flying', 7, '{"hp":68,"attack":55,"defense":55,"speed":42}', 'https://img.pokemondb.net/artwork/rowlet.jpg'),
(124, 'Dartrix', 'Grass', 'Flying', 7, '{"hp":78,"attack":75,"defense":75,"speed":52}', 'https://img.pokemondb.net/artwork/dartrix.jpg'),
(125, 'Decidueye', 'Grass', 'Ghost', 7, '{"hp":78,"attack":107,"defense":75,"speed":70}', 'https://img.pokemondb.net/artwork/decidueye.jpg'),
(126, 'Litten', 'Fire', NULL, 7, '{"hp":45,"attack":65,"defense":40,"speed":70}', 'https://img.pokemondb.net/artwork/litten.jpg'),
(127, 'Torracat', 'Fire', NULL, 7, '{"hp":65,"attack":85,"defense":50,"speed":90}', 'https://img.pokemondb.net/artwork/torracat.jpg'),
(128, 'Incineroar', 'Fire', 'Dark', 7, '{"hp":95,"attack":115,"defense":90,"speed":60}', 'https://img.pokemondb.net/artwork/incineroar.jpg'),
(129, 'Popplio', 'Water', NULL, 7, '{"hp":50,"attack":54,"defense":54,"speed":40}', 'https://img.pokemondb.net/artwork/popplio.jpg'),
(130, 'Brionne', 'Water', NULL, 7, '{"hp":60,"attack":69,"defense":69,"speed":50}', 'https://img.pokemondb.net/artwork/brionne.jpg'),
(131, 'Primarina', 'Water', 'Fairy', 7, '{"hp":80,"attack":74,"defense":74,"speed":60}', 'https://img.pokemondb.net/artwork/primarina.jpg'),
(132, 'Pikipek', 'Normal', 'Flying', 7, '{"hp":35,"attack":75,"defense":30,"speed":65}', 'https://img.pokemondb.net/artwork/pikipek.jpg'),
(133, 'Trumbeak', 'Normal', 'Flying', 7, '{"hp":55,"attack":85,"defense":50,"speed":75}', 'https://img.pokemondb.net/artwork/trumbeak.jpg'),
(134, 'Toucannon', 'Normal', 'Flying', 7, '{"hp":80,"attack":120,"defense":75,"speed":60}', 'https://img.pokemondb.net/artwork/toucannon.jpg'),
(135, 'Yungoos', 'Normal', NULL, 7, '{"hp":48,"attack":70,"defense":30,"speed":45}', 'https://img.pokemondb.net/artwork/yungoos.jpg'),
(136, 'Gumshoos', 'Normal', NULL, 7, '{"hp":88,"attack":110,"defense":60,"speed":45}', 'https://img.pokemondb.net/artwork/gumshoos.jpg'),
(137, 'Grubbin', 'Bug', NULL, 7, '{"hp":47,"attack":62,"defense":45,"speed":46}', 'https://img.pokemondb.net/artwork/grubbin.jpg'),
(138, 'Charjabug', 'Bug', 'Electric', 7, '{"hp":57,"attack":82,"defense":95,"speed":36}', 'https://img.pokemondb.net/artwork/charjabug.jpg'),
(139, 'Vikavolt', 'Bug', 'Electric', 7, '{"hp":77,"attack":70,"defense":90,"speed":43}', 'https://img.pokemondb.net/artwork/vikavolt.jpg'),
(140, 'Grookey', 'Grass', NULL, 8, '{"hp":50,"attack":65,"defense":50,"speed":65}', 'https://img.pokemondb.net/artwork/grookey.jpg'),
(141, 'Thwackey', 'Grass', NULL, 8, '{"hp":70,"attack":85,"defense":70,"speed":80}', 'https://img.pokemondb.net/artwork/thwackey.jpg'),
(142, 'Rillaboom', 'Grass', NULL, 8, '{"hp":100,"attack":125,"defense":90,"speed":85}', 'https://img.pokemondb.net/artwork/rillaboom.jpg'),
(143, 'Scorbunny', 'Fire', NULL, 8, '{"hp":50,"attack":71,"defense":40,"speed":69}', 'https://img.pokemondb.net/artwork/scorbunny.jpg'),
(144, 'Raboot', 'Fire', NULL, 8, '{"hp":65,"attack":86,"defense":60,"speed":94}', 'https://img.pokemondb.net/artwork/raboot.jpg'),
(145, 'Cinderace', 'Fire', NULL, 8, '{"hp":80,"attack":116,"defense":75,"speed":119}', 'https://img.pokemondb.net/artwork/cinderace.jpg'),
(146, 'Sobble', 'Water', NULL, 8, '{"hp":50,"attack":40,"defense":40,"speed":70}', 'https://img.pokemondb.net/artwork/sobble.jpg'),
(147, 'Drizzile', 'Water', NULL, 8, '{"hp":65,"attack":60,"defense":55,"speed":90}', 'https://img.pokemondb.net/artwork/drizzile.jpg'),
(148, 'Inteleon', 'Water', NULL, 8, '{"hp":70,"attack":85,"defense":65,"speed":120}', 'https://img.pokemondb.net/artwork/inteleon.jpg'),
(149, 'Rookidee', 'Flying', NULL, 8, '{"hp":38,"attack":47,"defense":35,"speed":57}', 'https://img.pokemondb.net/artwork/rookidee.jpg'),
(150, 'Corvisquire', 'Flying', NULL, 8, '{"hp":68,"attack":67,"defense":55,"speed":77}', 'https://img.pokemondb.net/artwork/corvisquire.jpg'),
(151, 'Corviknight', 'Flying', 'Steel', 8, '{"hp":98,"attack":87,"defense":105,"speed":67}', 'https://img.pokemondb.net/artwork/corviknight.jpg'),
(152, 'Blipbug', 'Bug', NULL, 8, '{"hp":25,"attack":20,"defense":20,"speed":45}', 'https://img.pokemondb.net/artwork/blipbug.jpg'),
(153, 'Dottler', 'Bug', 'Psychic', 8, '{"hp":50,"attack":35,"defense":80,"speed":30}', 'https://img.pokemondb.net/artwork/dottler.jpg'),
(154, 'Orbeetle', 'Bug', 'Psychic', 8, '{"hp":60,"attack":45,"defense":110,"speed":90}', 'https://img.pokemondb.net/artwork/orbeetle.jpg'),
(155, 'Nickit', 'Dark', NULL, 8, '{"hp":40,"attack":28,"defense":28,"speed":50}', 'https://img.pokemondb.net/artwork/nickit.jpg'),
(156, 'Thievul', 'Dark', NULL, 8, '{"hp":70,"attack":58,"defense":58,"speed":90}', 'https://img.pokemondb.net/artwork/thievul.jpg'),
-- Pokémon di nona generazione
(157, 'Sprigatito', 'Grass', NULL, 9, '{"hp":40,"attack":61,"defense":54,"speed":83}', 'https://img.pokemondb.net/artwork/sprigatito.jpg'),
(158, 'Floragato', 'Grass', NULL, 9, '{"hp":61,"attack":80,"defense":63,"speed":102}', 'https://img.pokemondb.net/artwork/floragato.jpg'),
(159, 'Meowscarada', 'Grass', 'Dark', 9, '{"hp":76,"attack":110,"defense":70,"speed":123}', 'https://img.pokemondb.net/artwork/meowscarada.jpg'),
(160, 'Fuecoco', 'Fire', NULL, 9, '{"hp":67,"attack":45,"defense":59,"speed":36}', 'https://img.pokemondb.net/artwork/fuecoco.jpg'),
(161, 'Crocalor', 'Fire', NULL, 9, '{"hp":81,"attack":55,"defense":78,"speed":49}', 'https://img.pokemondb.net/artwork/crocalor.jpg'),
(162, 'Skeledirge', 'Fire', 'Ghost', 9, '{"hp":104,"attack":75,"defense":100,"speed":66}', 'https://img.pokemondb.net/artwork/skeledirge.jpg'),
(163, 'Quaxly', 'Water', NULL, 9, '{"hp":55,"attack":65,"defense":45,"speed":50}', 'https://img.pokemondb.net/artwork/quaxly.jpg'),
(164, 'Quaxwell', 'Water', NULL, 9, '{"hp":70,"attack":85,"defense":65,"speed":65}', 'https://img.pokemondb.net/artwork/quaxwell.jpg'),
(165, 'Quaquaval', 'Water', 'Fighting', 9, '{"hp":85,"attack":120,"defense":80,"speed":85}', 'https://img.pokemondb.net/artwork/quaquaval.jpg'),
(166, 'Lechonk', 'Normal', NULL, 9, '{"hp":54,"attack":45,"defense":40,"speed":35}', 'https://img.pokemondb.net/artwork/lechonk.jpg'),
(167, 'Oinkologne', 'Normal', NULL, 9, '{"hp":110,"attack":100,"defense":75,"speed":65}', 'https://img.pokemondb.net/artwork/oinkologne.jpg'),
(168, 'Tarountula', 'Bug', NULL, 9, '{"hp":35,"attack":41,"defense":45,"speed":35}', 'https://img.pokemondb.net/artwork/tarountula.jpg'),
(169, 'Spidops', 'Bug', NULL, 9, '{"hp":60,"attack":79,"defense":92,"speed":35}', 'https://img.pokemondb.net/artwork/spidops.jpg'),
(170, 'Nymble', 'Bug', NULL, 9, '{"hp":33,"attack":46,"defense":40,"speed":45}', 'https://img.pokemondb.net/artwork/nymble.jpg'),
(171, 'Lokix', 'Bug', 'Dark', 9, '{"hp":71,"attack":102,"defense":78,"speed":92}', 'https://img.pokemondb.net/artwork/lokix.jpg');

INSERT INTO evolutions (base_pokemon_id, evolved_pokemon_id, evolution_trigger, trigger_detail) VALUES
(1, 2, 'level', '16'),
(2, 3, 'level', '32'),
(4, 5, 'level', '16'),
(5, 6, 'level', '36'),
(7, 8, 'level', '16'),
(8, 9, 'level', '36'),
(10, 11, 'level', '7'),
(11, 12, 'level', '10'),
(13, 14, 'level', '7'),
(14, 15, 'level', '10'),
(16, 17, 'item', 'Water Stone'),
(16, 18, 'item', 'Thunder Stone'),
(16, 19, 'item', 'Fire Stone'),
(16, 20, 'friendship', 'Daytime'),
(16, 21, 'friendship', 'Nighttime'),
(22, 23, 'friendship', 'None'),
(23, 24, 'item', 'Shiny Stone'),
(25, 26, 'level', '16'),
(26, 27, 'level', '32'),
(28, 29, 'level', '14'),
(29, 30, 'level', '36'), 
(31, 32, 'level', '18'), 
(32, 33, 'level', '30'),
(34, 35, 'level', '15'),
(36, 37, 'level', '20'),
(38, 39, 'level', '22'), 
(19, 40, 'friendship', 'None'),
(41, 20, 'friendship', 'None'),
(42, 24, 'friendship', 'None'), 
(43, 18, 'friendship', 'None'),
(44, 45, 'level', '16'), 
(45, 46, 'level', '36'), 
(47, 48, 'level', '16'), 
(48, 49, 'level', '36'),
(50, 51, 'level', '16'), 
(51, 52, 'level', '36'), 
(53, 54, 'level', '18'),
(55, 56, 'level', '20'),
(57, 58, 'level', '7'), 
(58, 59, 'level', '10'),
(57, 60, 'level', '7'), 
(60, 61, 'level', '10'),
(62, 63, 'level', '18'),
(63, 64, 'level', '32'), 
(65, 66, 'level', '14'),
(66, 67, 'level', '36'), 
(68, 69, 'level', '16'), 
(69, 70, 'level', '36'), 
(71, 72, 'level', '14'),
(72, 73, 'level', '34'), 
(74, 75, 'level', '15'), 
(76, 77, 'level', '15'), 
(77, 78, 'level', '30'), 
(79, 80, 'friendship', 'Daytime'), 
(80, 81, 'item', 'Shiny Stone'),
(82, 83, 'level', '17'),
(83, 84, 'level', '36'), 
(85, 86, 'level', '17'), 
(86, 87, 'level', '36'),
(88, 89, 'level', '17'), 
(89, 90, 'level', '36'), 
(91, 92, 'level', '20'), 
(93, 94, 'level', '16'),
(94, 95, 'level', '32'), 
(96, 97, 'level', '20'), 
(98, 99, 'item', 'Leaf Stone'), 
(100, 101, 'item', 'Water Stone'), 
(102, 103, 'item', 'Fire Stone'),
(104, 105, 'level', '16'), 
(105, 106, 'level', '36'), 
(107, 108, 'level', '16'), 
(108, 109, 'level', '36'), 
(110, 111, 'level', '16'), 
(111, 112, 'level', '36'),
(113, 114, 'level', '20'), 
(115, 116, 'level', '17'), 
(116, 117, 'level', '35'), 
(118, 119, 'level', '9'), 
(119, 120, 'level', '12'), 
(121, 122, 'level', '35'),
(123, 124, 'level', '17'), 
(124, 125, 'level', '34'), 
(126, 127, 'level', '17'), 
(127, 128, 'level', '34'), 
(129, 130, 'level', '17'), 
(130, 131, 'level', '34'),
(132, 133, 'level', '14'), 
(133, 134, 'level', '28'), 
(135, 136, 'level', '20'), 
(137, 138, 'level', '20'), 
(138, 139, 'item', 'Thunder Stone'),
(140, 141, 'level', '16'),
(141, 142, 'level', '35'),
(143, 144, 'level', '16'), 
(144, 145, 'level', '35'), 
(146, 147, 'level', '16'), 
(147, 148, 'level', '35'), 
(149, 150, 'level', '18'), 
(150, 151, 'level', '38'), 
(152, 153, 'level', '10'), 
(153, 154, 'level', '30'),
(155, 156, 'level', '18'),
(157, 158, 'level', '16'), 
(158, 159, 'level', '36'), 
(160, 161, 'level', '16'),
(161, 162, 'level', '36'), 
(163, 164, 'level', '16'), 
(164, 165, 'level', '36'),
(166, 167, 'level', '18'), 
(168, 169, 'level', '15'), 
(170, 171, 'level', '24');